### ISSUE TITLE
真机调试报错

### ISSUE THREAD

**Issue by yuanjilee** [Wildog/iOS-10-Steps-Widget#1]
你好，首先感谢分享。
看到展示效果很帮，想要在真机上运行，但是报错如下，是要申请相应的证书吗？
![image](https://cloud.githubusercontent.com/assets/9959986/18660382/aefa5e94-7f42-11e6-9782-a267744892b9.png)

**Comment by Wildog** [comment]
bundle identifier 必须是独特的，会联网认证，这个我已经用了，你可以改成 com.yuanjilee.steps.Widget 之类的, 三个 target 的 identifier 都得改一下

**Comment by yuanjilee** [comment]
thx~
